apiVersion: v1
kind: Secret
metadata:
  name: longhorn-ingress-auth
  namespace: longhorn-system
type: Opaque
data:
  auth: bTJRZTlWelJUOiQyeSQwNSRIS2x6Uy9mNFZ2eVljSkRzL3Z4Q3d1R2RvUThSUDBSWXZSYm01VFptWGh1VWY2OElCS0I3Lg==
