apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ingress-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.10.10.10-172.10.10.100
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ingress-adv
  namespace: metallb-system
spec:
  ipAddressPools:
  - ingress-pool
